"use strict";

const TOOL_MODULES = Object.freeze([
  require("./http-scan.js"),
  require("./read-http-audit.js"),
  require("./start-wave.js"),
  require("./route-surfaces.js"),
  require("./import-http-traffic.js"),
  require("./public-intel.js"),
  require("./import-static-artifact.js"),
  require("./static-scan.js"),
  require("./record-finding.js"),
  require("./read-findings.js"),
  require("./list-findings.js"),
  require("./write-chain-attempt.js"),
  require("./read-chain-attempts.js"),
  require("./write-verification-round.js"),
  require("./read-verification-round.js"),
  require("./write-evidence-packs.js"),
  require("./read-evidence-packs.js"),
  require("./write-grade-verdict.js"),
  require("./read-grade-verdict.js"),
  require("./init-session.js"),
  require("./read-session-state.js"),
  require("./transition-phase.js"),
  require("./apply-wave-merge.js"),
  require("./write-handoff.js"),
  require("./write-wave-handoff.js"),
  require("./wave-handoff-status.js"),
  require("./merge-wave-handoffs.js"),
  require("./read-wave-handoffs.js"),
  require("./log-dead-ends.js"),
  require("./log-coverage.js"),
  require("./wave-status.js"),
  require("./temp-email.js"),
  require("./signup-detect.js"),
  require("./auth-store.js"),
  require("./list-auth-profiles.js"),
  require("./auto-signup.js"),
  require("./read-state-summary.js"),
  require("./read-session-summary.js"),
  require("./set-operator-note.js"),
  require("./clear-operator-note.js"),
  require("./read-hunter-brief.js"),
  require("./read-tool-telemetry.js"),
  require("./read-pipeline-analytics.js"),
  require("./record-surface-leads.js"),
  require("./read-surface-leads.js"),
  require("./promote-surface-leads.js"),
]);

module.exports = {
  TOOL_MODULES,
};
